language: elixir

sudo: false

matrix:
  include:
    - otp_release: 21.0
      elixir: 1.8.1

script:
  - mix deps.get
  - mix deps.compile
  - mix format --check-formatted
  - mix dialyzer --halt-exit-status
  - mix test

cache:
  directories:
    - priv/plts
